// Starter list for the school search dropdown. FUOYE is first since that's
// the current user base. This isn't exhaustive — the dropdown also accepts
// free text, so a student/agent from a school not listed here can still
// type their own school name and it'll be saved as typed.
export const NIGERIAN_UNIVERSITIES = [
  'Federal University Oye-Ekiti (FUOYE)',
  'Federal University of Technology, Akure (FUTA)',
  'Ekiti State University (EKSU)',
  'Afe Babalola University (ABUAD)',
  'Obafemi Awolowo University (OAU)',
  'University of Ibadan (UI)',
  'University of Lagos (UNILAG)',
  'Lagos State University (LASU)',
  'Covenant University',
  'Babcock University',
  'Landmark University',
  "Redeemer's University",
  'Bowen University',
  'Lead City University',
  'Crawford University',
  'Joseph Ayo Babalola University',
  'Elizade University',
  'Wesley University',
  "Kings University",
  'McPherson University',
  'Precious Cornerstone University',
  'Bells University of Technology',
  'Caleb University',
  'Pan-Atlantic University',
  'Olabisi Onabanjo University (OOU)',
  'Tai Solarin University of Education (TASUED)',
  'Adekunle Ajasin University',
  'Osun State University',
  'Ambrose Alli University',
  'Delta State University',
  'University of Benin (UNIBEN)',
  'University of Port Harcourt (UNIPORT)',
  'Rivers State University',
  'University of Nigeria, Nsukka (UNN)',
  'Nnamdi Azikiwe University',
  'University of Calabar (UNICAL)',
  'Ahmadu Bello University (ABU)',
  'Bayero University Kano (BUK)',
  'Usmanu Danfodiyo University',
  'University of Ilorin (UNILORIN)',
  'Kwara State University',
  'University of Jos',
  'University of Maiduguri',
  'University of Abuja',
  'Nasarawa State University',
  'Federal University Lafia',
  'Federal University of Technology, Minna',
  'Federal University of Technology, Owerri',
  'Kaduna State University',
  'American University of Nigeria',
  'Nile University of Nigeria',
  'Baze University',
  'Veritas University',
]